// this code was autogenerated from PJS
(function($p) {

    var UserName = " ";
    var HIGHSCORE1 = 0;
    var HIGHSCORENAME1 = null;
    var HIGHSCORE2 = 0;
    var HIGHSCORENAME2 = null;
    var HIGHSCORE3 = 0;
    var HIGHSCORENAME3 = null;

    var arrays = $p.createJavaArray('int', [12, 2]);
    var gapWidth = 50;
    var gapHeight = 400;
    var scootTime = 0;
    var objectY = 400;
    var currvelocity = 0;
    var STARTMODE = true;
    var topLine = 50;
    var bottomLine = 700;
    var ballSize = 15;
    var wallSpeed = 3;
    var oldTime = 0;
    var dropRiseSpeed = 8;
    var currentLVL = 1;
    var finishWall = 4200;
    var numberPassed = 1;
    var LIVES = 3;
    var DEMOTELIVES = false;
    var highscore = 1;

    var COUNTDOWNBEGIN = false;
    var countdown = 0;
    var interval = 300;

    var UPDOWNFRAMES = 0;
    var GOINGUP = false;

    var NumberOfPlays = 0;

    function setup() {
        $p.size(1000, 750);
        $p.background(0);
        $p.stroke(255);

        var lines = $p.loadStrings("http://students.washington.edu/njcr/BallJump_10Levels/HighScores.txt");
        HIGHSCORENAME1 = lines[0];
        HIGHSCORE1 = $p.parseInt(lines[1]);

        HIGHSCORENAME2 = lines[2];
        HIGHSCORE2 = $p.parseInt(lines[3]);

        HIGHSCORENAME3 = lines[4];
        HIGHSCORE3 = $p.parseInt(lines[5]);

        NumberOfPlays = $p.parseInt(lines[6]) + 1;
        lines[6] = $p.str(NumberOfPlays);
    }
    $p.setup = setup;
    setup = setup.bind($p);

    var NONAMEYET = true;

    function draw() {
        if (LIVES == 0) {
            ShowHighScore();
        } else if (STARTMODE) {
            homeScreen();
            initialize();
            if (currentLVL == 1 & NONAMEYET) {
                $p.fill(255);
                $p.textSize(72);
                $p.text("Enter your name!", 50, 100);
                KeyBoard();
            } else if ($p.__mousePressed) {
                STARTMODE = false;
            }
        } else if ($p.frameCount < countdown) {
            $p.background(0);
            $p.fill(155);
            $p.textSize(72);
            if (currentLVL == 1) {
                $p.text("Level 1 - Normal", 100, 200);
            }
            if (currentLVL == 2) {
                $p.text("Level 2 - Shrinking Gap", 100, 200);
            }
            if (currentLVL == 3) {
                $p.text("Level 3 - Growing Ball", 100, 200);
            }
            if (currentLVL == 4) {
                $p.text("Level 4 - Going Fast", 100, 200);
            }
            if (currentLVL == 5) {
                $p.text("Level 5 - Tunnel", 100, 200);
            }
            if (currentLVL == 6) {
                $p.text("Level 6 - Moving Gaps", 100, 200);
            }
            if (currentLVL == 7) {
                $p.text("Level 7 - High Gravity", 100, 200);
            }
            if (currentLVL == 8) {
                $p.text("Level 8 - High Density", 100, 200);
            }
            if (currentLVL == 9) {
                $p.text("Level 9 - Low Contrast", 100, 200);
            }
            if (currentLVL == 10) {
                $p.text("Level 10 - Death Combo", 100, 200);
            }
            $p.text($p.parseInt(((countdown - $p.frameCount) / 100) + 1), 400, 400);
        } else {
            if (finishWall < 50) {
                FinishedLevel();
            } else if (LostGame()) {
                $p.fill(204, 0, 0);
                $p.textSize(72);
                $p.text("You failed!", 50, 300);
                if (numberPassed > highscore) {
                    highscore = numberPassed;
                }
                $p.text("Lives Left: " + (LIVES - 1), 50, 400);
                if ($p.__mousePressed) {
                    STARTMODE = true;
                    countdown = $p.frameCount + interval;
                    LIVES = LIVES - 1;
                }
            } else {
                if (currentLVL == 9 | currentLVL == 10) {
                    $p.background(160);
                } else {
                    $p.background(0, 100, 150);
                }
                if (currentLVL == 2 | currentLVL == 10) {
                    if (($p.frameCount - 5) > oldTime) {
                        oldTime = $p.frameCount;
                        gapHeight = gapHeight - 1;
                    }
                }
                if (currentLVL == 3 | currentLVL == 10) {
                    if (($p.frameCount - 5) > oldTime) {
                        oldTime = $p.frameCount;
                        ballSize = ballSize + 1;
                    }
                }
                if (currentLVL == 4 | currentLVL == 10) {
                    if (($p.frameCount - 10) > oldTime) {
                        oldTime = $p.frameCount;
                        wallSpeed = wallSpeed + 1;
                    }
                }
                if (currentLVL == 5 | currentLVL == 10) {
                    gapWidth = 300;
                }

                if (currentLVL == 6 | currentLVL == 10) {
                    UPDOWNFRAMES = UPDOWNFRAMES + 1;
                    for (var i = 0; i < arrays.length; i++) {
                        if (GOINGUP) {
                            if (UPDOWNFRAMES < 50) {
                                if (arrays[i][1] > topLine) {
                                    arrays[i][1] = arrays[i][1] - 1;
                                }
                            } else {
                                GOINGUP = false;
                                UPDOWNFRAMES = 0;
                            }
                        } else {
                            if (UPDOWNFRAMES < 50) {
                                if (arrays[i][1] < (bottomLine - gapHeight)) {
                                    arrays[i][1] = arrays[i][1] + 1;
                                }
                            } else {
                                GOINGUP = true;
                                UPDOWNFRAMES = 0;
                            }
                        }
                    }
                }
                if (currentLVL == 7 | currentLVL == 10) {
                    dropRiseSpeed = 15;
                }
                if (currentLVL == 9 | currentLVL == 10) {
                    $p.stroke(170);
                    $p.fill(170);
                } else {
                    $p.fill(255);
                }

                for (var i = 0; i < arrays.length; i++) {
                    $p.rect(arrays[i][0], 1, gapWidth, arrays[i][1]);
                    $p.rect(arrays[i][0], arrays[i][1] + gapHeight, gapWidth, 749 - (arrays[i][1] + gapHeight));
                }

                $p.fill(0, 255, 50);
                $p.rect(finishWall, 1, 1000, 750);

                Scoot();

                $p.fill(255);
                $p.rect(0, 0, 1000, topLine);
                $p.rect(0, bottomLine, 1000, 750 - bottomLine);
                $p.fill(164);
                $p.textSize(24);
                $p.text("" + numberPassed, 5, 20);

                if ($p.__mousePressed && currvelocity < 10) {
                    currvelocity = currvelocity + dropRiseSpeed;
                } else if (currvelocity > -dropRiseSpeed) {
                    currvelocity = currvelocity - 1;
                }
                objectY = objectY - currvelocity;
                DrawLives();
                DrawBouncer();
            }
        }
    }
    $p.draw = draw;
    draw = draw.bind($p);

    function FinishedLevel() {
        currentLVL = currentLVL + 1;
        STARTMODE = true;
        LIVES = LIVES + 1;
        countdown = $p.frameCount + interval;
    }
    $p.FinishedLevel = FinishedLevel;
    FinishedLevel = FinishedLevel.bind($p);

    function Scoot() {
        numberPassed = $p.parseInt(currentLVL * 100 + ((4200 - finishWall) / 50));
        for (var i = 0; i < arrays.length; i++) {
            arrays[i][0] = arrays[i][0] - wallSpeed;
        }
        finishWall = finishWall - wallSpeed;
    }
    $p.Scoot = Scoot;
    Scoot = Scoot.bind($p);

    function homeScreen() {
        if (currentLVL == 1 & !NONAMEYET) {

        } else if (currentLVL == 10) {
            $p.background(155);
            $p.fill(0);
            $p.textSize(64);
            $p.text("Good Luck!", 50, 400);
        } else {
            $p.fill(0);
            $p.textSize(64);
            $p.text("Completed Level " + (currentLVL - 1), 50, 400);
        }
    }
    $p.homeScreen = homeScreen;
    homeScreen = homeScreen.bind($p);

    function initialize() {
        objectY = 400;
        currvelocity = 0;
        finishWall = 4200;
        wallSpeed = 3;
        gapHeight = 400;
        ballSize = 15;
        gapWidth = 50;
        dropRiseSpeed = 8;

        for (var i = 0; i < arrays.length; i++) {
            if (currentLVL == 8) {
                arrays[i][0] = i * 150 + 500;
                finishWall = 2100;
            } else {
                arrays[i][0] = i * 300 + 500;
            }
            arrays[i][1] = $p.parseInt($p.random(topLine, bottomLine - gapHeight));
        }
    }
    $p.initialize = initialize;
    initialize = initialize.bind($p);

    function LostGame() {
        if (objectY > (bottomLine - (ballSize / 2)) | objectY < (topLine + (ballSize / 2))) {
            return true;
        }
        for (var i = 0; i < arrays.length; i++) {
            if ((arrays[i][0] < 50 && arrays[i][0] > (50 - gapWidth)) && objectY < (arrays[i][1] + (ballSize / 2)) | (arrays[i][0] < 50 && arrays[i][0] > (50 - gapWidth) && objectY > (arrays[i][1] + gapHeight - (ballSize / 2)))) {
                return true;
            }
        }
        return false;
    }
    $p.LostGame = LostGame;
    LostGame = LostGame.bind($p);

    function DrawLives() {
        for (var i = 0; i < LIVES; i++) {
            $p.stroke(255);
            $p.fill(255, 255, 255);
            $p.arc(900 - i * 50, 25, 2 * 15, 2 * 15, $p.PI, 10);
            $p.fill(255, 0, 0);
            $p.arc(900 - i * 50, 25, 2 * 15, 2 * 15, -$p.PI, 0);
            $p.strokeWeight(1);
            $p.fill(0);
            $p.rect(900 - i * 50 - (15), 25 - 15 / 6, 2 * 15, 15 / 3);
            $p.ellipse(900 - i * 50, 25, 15, 15);
            $p.fill(255, 255, 255);
            $p.ellipse(900 - i * 50, 25, 15 - 15 / 3, 15 - 15 / 3);
        }
    }
    $p.DrawLives = DrawLives;
    DrawLives = DrawLives.bind($p);

    function DrawBouncer() {
        $p.fill(255, 255, 255);
        $p.arc(50, objectY, 2 * ballSize, 2 * ballSize, $p.PI, 10);
        $p.fill(255, 0, 0);
        $p.arc(50, objectY, 2 * ballSize, 2 * ballSize, -$p.PI, 0);
        $p.strokeWeight(0);
        $p.fill(0);
        $p.rect(50 - (ballSize), objectY - ballSize / 6, 2 * ballSize, ballSize / 3);
        $p.ellipse(50, objectY, ballSize, ballSize);
        $p.fill(255, 255, 255);
        $p.ellipse(50, objectY, ballSize - ballSize / 3, ballSize - ballSize / 3);
    }
    $p.DrawBouncer = DrawBouncer;
    DrawBouncer = DrawBouncer.bind($p);

    function ShowHighScore() {
        $p.background(0);
        $p.fill(255);
        var list = $p.createJavaArray('String', [7]);
        if (highscore > HIGHSCORE1) {
            $p.text("You Got First Place!", 50, 100);
            list[0] = UserName;
            list[1] = "" + highscore;
            list[2] = HIGHSCORENAME1;
            list[3] = "" + HIGHSCORE1;
            list[4] = HIGHSCORENAME2;
            list[5] = "" + HIGHSCORE2;
        } else if (highscore > HIGHSCORE2) {
            $p.text("You Got Second Place!", 50, 100);
            list[0] = HIGHSCORENAME1;
            list[1] = "" + HIGHSCORE1;
            list[2] = UserName;
            list[3] = "" + highscore;
            list[4] = HIGHSCORENAME2;
            list[5] = "" + HIGHSCORE2;
        } else if (highscore > HIGHSCORE3) {
            $p.text("You Got third Place!", 50, 100);
            list[0] = HIGHSCORENAME1;
            list[1] = "" + HIGHSCORE1;
            list[2] = HIGHSCORENAME2;
            list[3] = "" + HIGHSCORE2;
            list[4] = UserName;
            list[5] = "" + highscore;
        } else {
            list[0] = HIGHSCORENAME1;
            list[1] = "" + HIGHSCORE1;
            list[2] = HIGHSCORENAME2;
            list[3] = "" + HIGHSCORE2;
            list[4] = HIGHSCORENAME3;
            list[5] = "" + HIGHSCORE3;
        }
        $p.background(0);
        $p.fill(255);
        $p.textSize(32);
        $p.text("Refresh to restart!", 50, 100);
        $p.text("Highest Score: " + list[0] + " " + list[1], 50, 300);
        $p.text("2nd Highest Score: " + list[2] + " " + list[3], 50, 400);
        $p.text("3rd Highest Score: " + list[4] + " " + list[5], 50, 500);
        $p.textSize(16);
        $p.text("Number of plays: " + NumberOfPlays, 700, 700);
        list[6] = $p.str(NumberOfPlays);
    }
    $p.ShowHighScore = ShowHighScore;
    ShowHighScore = ShowHighScore.bind($p);

    var LastPress = 0;

    function KeyBoard() {
        for (var i = 0; i < 3; i++) {
            for (var j = 0; j < 9; j++) {
                $p.fill(155);
                $p.rect(j * 100 + 100, i * 100 + 200, 75, 75);
                $p.fill(225);
                $p.textSize(32);
                if (j == 8 & i == 2) {
                    $p.text("_", j * 100 + 110, i * 100 + 250);
                } else {
                    $p.text($p.str($p.parseChar((j) + (i * 9) + 65)), j * 100 + 110, i * 100 + 250);
                }
            }
        }
        $p.fill(204, 0, 0);
        $p.rect(700, 600, 100, 50);

        $p.fill(225);
        $p.textSize(32);
        $p.text("Enter!", 700, 640);

        $p.text(UserName, 100, 650);

        if ($p.__mousePressed & $p.frameCount - 30 > LastPress) {
            LastPress = $p.frameCount;
            if ($p.mouseX < 800 & $p.mouseX > 700 & $p.mouseY < 650 & $p.mouseY > 600) {
                NONAMEYET = false;
            }
            if ($p.mouseX < 175 & $p.mouseX > 100 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "A";
            }
            if ($p.mouseX < 275 & $p.mouseX > 200 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "B";
            }
            if ($p.mouseX < 375 & $p.mouseX > 300 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "C";
            }
            if ($p.mouseX < 475 & $p.mouseX > 400 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "D";
            }
            if ($p.mouseX < 575 & $p.mouseX > 500 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "E";
            }
            if ($p.mouseX < 675 & $p.mouseX > 600 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "F";
            }
            if ($p.mouseX < 775 & $p.mouseX > 700 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "G";
            }
            if ($p.mouseX < 875 & $p.mouseX > 800 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "H";
            }
            if ($p.mouseX < 975 & $p.mouseX > 900 & $p.mouseY < 275 & $p.mouseY > 200) {
                UserName = UserName + "I";
            }
            if ($p.mouseX < 175 & $p.mouseX > 100 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "J";
            }
            if ($p.mouseX < 275 & $p.mouseX > 200 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "K";
            }
            if ($p.mouseX < 375 & $p.mouseX > 300 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "L";
            }
            if ($p.mouseX < 475 & $p.mouseX > 400 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "M";
            }
            if ($p.mouseX < 575 & $p.mouseX > 500 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "N";
            }
            if ($p.mouseX < 675 & $p.mouseX > 600 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "O";
            }
            if ($p.mouseX < 775 & $p.mouseX > 700 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "P";
            }
            if ($p.mouseX < 875 & $p.mouseX > 800 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "Q";
            }
            if ($p.mouseX < 975 & $p.mouseX > 900 & $p.mouseY < 375 & $p.mouseY > 300) {
                UserName = UserName + "R";
            }
            if ($p.mouseX < 175 & $p.mouseX > 100 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "S";
            }
            if ($p.mouseX < 275 & $p.mouseX > 200 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "T";
            }
            if ($p.mouseX < 375 & $p.mouseX > 300 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "U";
            }
            if ($p.mouseX < 475 & $p.mouseX > 400 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "V";
            }
            if ($p.mouseX < 575 & $p.mouseX > 500 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "W";
            }
            if ($p.mouseX < 675 & $p.mouseX > 600 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "X";
            }
            if ($p.mouseX < 775 & $p.mouseX > 700 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "Y";
            }
            if ($p.mouseX < 875 & $p.mouseX > 800 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "Z";
            }
            if ($p.mouseX < 975 & $p.mouseX > 900 & $p.mouseY < 475 & $p.mouseY > 400) {
                UserName = UserName + "_";
            }
        }
    }
    $p.KeyBoard = KeyBoard;
    KeyBoard = KeyBoard.bind($p);
})